# Use Node.js base image
FROM node:18

# Set working directory
WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install

# Copy rest of the app files
COPY . .

# Expose the port the app runs on
EXPOSE 5000

# Run the app
CMD ["node", "app.js"]
